# Generated by Django 2.2.1 on 2019-05-21 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTableDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=255, null=True)),
                ('Lname', models.CharField(max_length=255, null=True)),
                ('Mobile', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('State', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=10000000, null=True)),
                ('Zip', models.CharField(blank=True, max_length=255, null=True)),
                ('Pic', models.TextField(blank=True, null=True)),
                ('ISActive', models.BooleanField(default=False, null=True)),
                ('Activation_Key', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
