# Generated by Django 2.2.1 on 2019-05-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(blank=True, max_length=100, null=True)),
                ('Telephone', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=3000)),
            ],
        ),
    ]
