# Generated by Django 2.2.1 on 2019-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='icon_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='states',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
