# Generated by Django 2.2.1 on 2019-05-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0002_auto_20190520_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=30000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, default=0.0, max_digits=25, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, default=0.0, max_digits=25, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_url', models.CharField(blank=True, max_length=30000, null=True)),
                ('property_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=30000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True)),
                ('presented_company', models.CharField(blank=True, max_length=10000, null=True)),
                ('presented_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.CharField(blank=True, max_length=30000, null=True)),
                ('property_link', models.CharField(blank=True, max_length=30000, null=True)),
                ('property_title', models.CharField(blank=True, max_length=10000, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10000, null=True)),
                ('active_bool', models.BooleanField(default=True)),
            ],
        ),
    ]
