# Generated by Django 2.2.1 on 2019-05-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0003_property_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_detail',
            name='post_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='property_detail',
            name='price_type',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='property_detail',
            name='property_area',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='property_detail',
            name='zipcode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
