# Generated by Django 2.2.1 on 2019-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0004_auto_20190522_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_detail',
            name='features',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='property_detail',
            name='overview',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
