# Generated by Django 2.2.1 on 2019-05-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0005_auto_20190522_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_detail',
            name='one_pic',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
