# Generated by Django 2.2.1 on 2019-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0007_auto_20190527_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_detail',
            name='destag',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='property_detail',
            name='subspace_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='active_bool',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
