# Generated by Django 2.2.1 on 2019-05-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0010_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Property_Type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
