# Generated by Django 2.2.2 on 2019-06-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0013_user_favourites_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_favourites',
            old_name='created',
            new_name='created_at',
        ),
    ]
