# Generated by Django 2.2.2 on 2019-06-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0014_auto_20190612_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_detail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='property_area',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
