# Generated by Django 2.2.2 on 2019-06-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0015_auto_20190613_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_detail',
            name='property_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
    ]
