# Generated by Django 2.2.2 on 2019-06-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offices', '0017_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_detail',
            old_name='county',
            new_name='country',
        ),
        migrations.AddField(
            model_name='property_detail',
            name='overviewtag',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
